# Generated by Django 3.0.6 on 2020-06-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_chat_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='from_user',
            new_name='author',
        ),
    ]
